language: clojure
lein: 2.9.1

before_install:
  - sudo pip install ansible docker

sudo: required

services: docker

dist: bionic

cache:
  directories:
    - $HOME/.m2
    - $HOME/travis-cache
    - $HOME/build-data/downloads

jdk:
  - openjdk9

env:
  - LD_LIBRARY_PATH=/opt/laundry/lib64 CI_CACHE=$HOME/travis-cache DOWNLOAD_DIR=$HOME/travis-cache

script:
  - test/ci-tests-lein.sh

after_failure:
  - sudo journalctl -u laundry.service
