- hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      yum:
        name:
          - docker
          - git
          - java-1.8.0-openjdk-headless
    - systemd:
        name: docker
        enabled: yes
    - group:
        name: docker
      notify: restart docker
  handlers:
    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
