- hosts: all
  become: yes
  vars:
    docker_users:
      - laundry
    # https://github.com/geerlingguy/ansible-role-pip/issues/24
    pip_package: python3-pip
  pre_tasks:
    - user:
        name: laundry
    # TODO Remove this when docker-ce packages are released officially for CentOS 8
    - name: Install containerd.io manually as a workaround
      yum:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
  roles:
    - geerlingguy.docker
  tasks:
    - name: Install dependencies
      yum:
        name:
          - git
          - java-1.8.0-openjdk-headless
    - get_url:
        url: "{{ gvisor_url }}"
        dest: "{{ gvisor_binary_path }}"
        checksum: "{{ gvisor_checksum }}"
        mode: 0755
    - name: Calculate checksum for docker daemon.json
      stat:
        path: /etc/docker/daemon.json
      register: daemon_before
    - name: Configure docker to use gvisor
      command: /usr/local/bin/runsc install -- --platform=ptrace
      changed_when: False
    - name: Calculate checksum for docker daemon.json
      stat:
        path: /etc/docker/daemon.json
      register: daemon_after
    - debug:
        msg: Docker daemon.json has been changed by runsc install
      changed_when: "(not daemon_before.stat.exists) or (daemon_before.stat.checksum != daemon_after.stat.checksum)"
      notify: restart docker
    - file:
        path: "{{ laundry_home }}"
        state: directory
        mode: 0700
        owner: "{{ laundry_user }}"
        group: "{{ laundry_user }}"
    - copy:
        src: "{{ laundry_uberjar }}"
        dest: "{{ laundry_home }}/laundry.jar"
        backup: yes
        owner: "{{ laundry_user }}"
        group: "{{ laundry_user }}"
      notify: restart laundry
    - set_fact:
        api_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits') }}"
    - name: Write API key if it does not exist
      copy:
        content: "{{ api_key }}\n"
        dest: "{{ laundry_api_key_path }}"
        force: no
        mode: 0600
        owner: "{{ laundry_user }}"
        group: "{{ laundry_user }}"
    - template:
        src: laundry.service.j2
        dest: /etc/systemd/system/laundry.service
      notify: restart laundry
  handlers:
    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
    - name: restart laundry
      systemd:
        daemon_reload: yes
        enabled: yes
        name: laundry.service
        state: restarted
